version: "3.4"
services:
  postgres:
    image: timescale/timescaledb:1.3.0-pg10
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: santiment

  influxdb:
    image: influxdb
    ports:
      - "8086"
  sanbase:
    build:
      context: .
      dockerfile: Dockerfile-dev

    volumes:
      - ./:/app:delegated

    hostname: sanbase_host

    command: sh -c "elixir --sname sanbase --cookie sanbase -S mix phx.server"
    expose:
      - 4000
    ports:
      - "4000:4000"

    depends_on:
      - postgres
      - influxdb

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/santiment
      TIMESCALE_DATABASE_URL: postgres://postgres:postgres@postgres:5432/santiment_timescale
      ADMIN_BASIC_AUTH_USERNAME: admin
      ADMIN_BASIC_AUTH_PASSWORD: admin
      INFLUXDB_HOST: influxdb
      WEBSITE_URL: http://localhost:4000
      PUBLIC_URL: http://localhost:4000
      PARITY_URL: http://parity-optimized:8545
      TECH_INDICATORS_URL: http://tech-indicators.default.svc.cluster.local
      CLICKHOUSE_DATABASE_URL: clickhouse://clickhouse-proxy.default.svc.cluster.local:8123/default
