version: "3.4"
services:
  postgres:
    image: timescale/timescaledb:1.4.0-pg10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
      target: builder

    depends_on:
      - postgres
      - influxdb

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/santiment
      TIMESCALE_DATABASE_URL: postgres://postgres:postgres@postgres:5432/santiment_timescale
      INFLUXDB_HOST: influxdb
