version: '3.4'
services:
  postgres:
    image: timescale/timescaledb:0.10.1-pg10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: santiment
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
  sanbase:
    build:
      context: .
      dockerfile: Dockerfile-dev

    volumes:
      - ./:/app:cached

    command: sh -c "mix deps.get && mix deps.compile && mix ecto.setup_all && cd assets/; yarn install; cd ../app; yarn install; cd .. && iex -S mix phx.server"
    expose:
      - 3000
      - 4000
    ports:
      - "4000:4000"
      - "3000:3000"

    depends_on:
      - postgres
      - influxdb

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/santiment
      TIMESCALE_DATABASE_URL: postgres://postgres:postgres@postgres:5432/santiment
      ADMIN_BASIC_AUTH_USERNAME: admin
      ADMIN_BASIC_AUTH_PASSWORD: admin
      INFLUXDB_HOST: influxdb
      WEBSITE_URL: http://localhost:4000
      PUBLIC_URL: http://localhost:4000
